definitions:
  domain.Link:
    properties:
      finalURL:
        type: string
      id:
        type: integer
      original:
        type: string
      shortened:
        type: string
    type: object
  web.ShortenURL:
    properties:
      alias:
        type: string
      domain:
        type: string
      url:
        type: string
    required:
    - url
    type: object
  web.errorResponse:
    properties:
      message:
        type: string
      status:
        type: string
      statusCode:
        type: integer
      timeStamp:
        type: string
    type: object
info:
  contact:
    name: Ronilson Alves
    url: https://www.linkedin.com/in/ronilsonalves
  description: This API provide endpoints to link shortning.
  license:
    name: MIT
    url: https://github.com/ronilsonalves/go-lnk/blob/main/LICENSE.md
  termsOfService: https://github.com/ronilsonalves/go-lnk/blog/main/LICENSE.md
  title: Go lnk API
  version: "1.0"
paths:
  /{shortened}:
    get:
      consumes:
      - application/json
      description: Redirect to original URL
      parameters:
      - description: Shortened URL
        in: path
        name: shortened
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Redirect to original URL
      tags:
      - Links
  /api/v1/links:
    post:
      consumes:
      - application/json
      description: Create a shortened link from a long URL.
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.ShortenURL'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Link'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Create a shortened link from a URL address and a provided alias
      tags:
      - Links
swagger: "2.0"
